Repository depromeet/InsightOut-client, pull requests merged in 2023-07, with the labels that each got.

#109 feat: 자기소개서 - 맞춤법 검사 api
  src/apis/resume/spellCheck.ts
  src/apis/resume/types/spellCheck.ts
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/components/SpellChecker/SpellChecker.stories.tsx
  src/features/resume/components/SpellChecker/SpellChecker.tsx
  src/features/resume/hooks/useSpellCheckResult.ts
  src/features/resume/store/index.ts
  src/features/resume/types/store.ts
  src/features/resume/utils/formatSpellCheckResponse.ts
  src/hooks/reactQuery/resume/mutation.ts
  src/hooks/reactQuery/resume/spellCheck/mutation.ts
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#110 feat: 자기소개서 - 내 경험카드 퍼블리싱
  src/app/globals.css
  src/app/resumes/layout.tsx
  src/components/Icon/IconCards.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCard.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardDetail.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
  src/features/resume/components/MyExperienceCard/MyExperienceCard.stories.tsx
  src/features/resume/components/MyExperienceCard/MyExperienceCard.tsx
  src/shared/@types/global.d.ts
Labels: :lipstick: STYLE, :sparkles: FEATURE

#113 feat: 회원가입 + 온보딩 및 로그인
  .vscode/settings.json
  next.config.js
  src/apis/auth/auth.ts
  src/apis/auth/types/auth.ts
  src/apis/onboarding/onboarding.ts
  src/apis/user/types/user.ts
  src/apis/user/user.ts
  src/app/template.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Icon/IconGnbMyPage.tsx
  src/components/Icon/jobCategories/IconAdvertising.tsx
  src/components/Icon/jobCategories/IconBio.tsx
  src/components/Icon/jobCategories/IconConstruction.tsx
  src/components/Icon/jobCategories/IconCustomerService.tsx
  src/components/Icon/jobCategories/IconDesign.tsx
  src/components/Icon/jobCategories/IconDevelopment.tsx
  src/components/Icon/jobCategories/IconEducation.tsx
  src/components/Icon/jobCategories/IconEngineering.tsx
  src/components/Icon/jobCategories/IconFinance.tsx
  src/components/Icon/jobCategories/IconGameProduction.tsx
  src/components/Icon/jobCategories/IconHumanResource.tsx
  src/components/Icon/jobCategories/IconLaw.tsx
  src/components/Icon/jobCategories/IconLogistics.tsx
  src/components/Icon/jobCategories/IconManagement.tsx
  src/components/Icon/jobCategories/IconManufacturing.tsx
  src/components/Icon/jobCategories/IconMarketing.tsx
  src/components/Icon/jobCategories/IconMedia.tsx
  src/components/Icon/jobCategories/IconMedical.tsx
  src/components/Icon/jobCategories/IconPublicWelfare.tsx
  src/components/Icon/jobCategories/IconRetail.tsx
  src/components/Icon/jobCategories/IconSales.tsx
  src/components/Icon/jobCategories/IconTrade.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalHeader.tsx
  src/features/auth/components/AuthModal/AuthModal.tsx
  src/features/auth/components/AuthModal/CategoryCard/CategoryCard.module.scss
  src/features/auth/components/AuthModal/CategoryCard/CategoryCard.stories.tsx
  src/features/auth/components/AuthModal/CategoryCard/CategoryCard.tsx
  src/features/auth/components/AuthModal/ModalContents/CategoriesContents.stories.tsx
  src/features/auth/components/AuthModal/ModalContents/CategoriesContents.tsx
  src/features/auth/components/AuthModal/ModalContents/SignUpContent.stories.tsx
  src/features/auth/components/AuthModal/ModalContents/SignUpContents.tsx
  src/features/auth/components/AuthModal/ModalContents/StartNowContents.stories.tsx
  src/features/auth/components/AuthModal/ModalContents/StartNowContents.tsx
  src/features/auth/components/AuthModal/ModalContents/WelcomeContents.stories.tsx
  src/features/auth/components/AuthModal/ModalContents/WelcomeContents.tsx
  src/features/auth/components/Providers/AuthProvider.tsx
  src/features/auth/constants/api.ts
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/auth/store/index.ts
  src/features/auth/types/store.ts
  src/shared/constants/api.ts
  src/shared/constants/user.ts
  src/shared/store/types/user.ts
  src/shared/store/user.ts
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#104 feat: Aside 기능 구현
  src/features/resume/components/Aside/Aside.tsx
  src/features/resume/components/Aside/DeleteModal.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Title.tsx
  src/features/resume/hooks/useResumeListWithUpdatedTitle.ts
  src/hooks/reactQuery/resume/mutation.ts
Labels: :sparkles: FEATURE

#117 feat: 자기소개서 - 첫 진입 화면 온보딩
  src/app/template.tsx
  src/components/Providers/OnboardingProvider.tsx
  src/components/Tooltip/Tooltip.tsx
  src/features/resume/components/Aside/Aside.tsx
  src/hooks/reactQuery/onboarding/mutation.ts
  src/shared/store/user.ts
Labels: :sparkles: FEATURE

#120 feat: 홈페이지
  .storybook/main.ts
  .vscode/settings.json
  public/images/home/img-home-1.png
  public/images/home/img-home-2.png
  public/images/home/img-home-3.png
  public/images/home/img-home-4.png
  public/images/home/img-home-ellipsis-left.png
  public/images/home/img-home-ellipsis-right.png
  public/images/home/img-home-experience-1.png
  public/images/home/img-home-experience-2.png
  public/images/home/img-home-experience-3.png
  public/images/home/img-home-experience-4.png
  public/images/home/img-home-logo.png
  public/images/home/img-home-looper-1.png
  public/images/home/img-home-looper-2.png
  public/images/home/img-home-looper-3.png
  public/images/home/img-home-looper-4.png
  public/images/home/img-home-looper-5.png
  src/app/page.tsx
  src/app/template.tsx
  src/components/Badge/Badge.module.scss
  src/components/Badge/Badge.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Home/AnalyzeCard.tsx
  src/components/Home/FeedbackForm.tsx
  src/components/Home/Home.tsx
  src/components/Home/Looper/Looper.module.scss
  src/components/Home/Looper/Looper.tsx
  src/components/Home/Looper/LooperCard.tsx
  src/components/Home/Looper/index.ts
  src/components/Home/StartButton.tsx
  src/components/Icon/IconChevronRight.tsx
  src/components/Icon/IconPairQuotation.tsx
Labels: :lipstick: STYLE, :sparkles: FEATURE

#118 Feat: collection resume api연동
  package.json
  public/images/card1.png
  src/apis/resume/count.ts
  src/apis/resume/resume.ts
  src/apis/resume/title.ts
  src/apis/resume/types/count.ts
  src/apis/resume/types/resume.ts
  src/apis/resume/types/title.ts
  src/app/collection/layout.tsx
  src/app/collection/resumes/page.tsx
  src/app/collection/template.tsx
  src/app/globals.css
  src/components/Badge/Badge.module.scss
  src/components/Button/TextButton.module.scss
  src/components/Icon/IconClock.tsx
  src/components/Icon/IconHeart.tsx
  src/features/collection/components/cards/ResumeAnswerModalCard.tsx
  src/features/collection/components/cards/ResumeCard.tsx
  src/features/collection/components/nav/ChipListNav.tsx
  src/features/collection/constants/index.ts
  src/features/collection/types/index.ts
  src/hooks/reactQuery/resume/query.ts
  src/shared/constants/tabs.ts
  src/shared/utils/addPlusMarkOver99.ts
  src/shared/utils/formatUpdateAt.ts
  src/shared/utils/queryKeys.ts
  src/styles/theme/components/modalTheme.ts
  yarn.lock
Labels: :sparkles: FEATURE

#123 feat: 경험카드 모아보기 - 무한스크롤 적용
  src/apis/experience/types/experience.ts
  src/app/collection/experiences/page.tsx
  src/hooks/reactQuery/experience/qeury.ts
  src/hooks/useIntersection.ts
Labels: :sparkles: FEATURE

#116 Feat/collection experiences api
  src/apis/experience/experience.ts
  src/apis/experience/types/experience.ts
  src/app/collection/experiences/page.tsx
  src/app/collection/resumes/page.tsx
  src/app/collection/template.tsx
  src/components/Icon/IconClock.tsx
  src/components/Icon/index.ts
  src/components/Modal/ModalHeader.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceCard.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceModal.tsx
  src/features/collection/components/cards/ExperienceListCard/ExperienceListCard.tsx
  src/features/collection/components/cards/MotionBox.tsx
  src/features/collection/components/nav/ChipListNav.tsx
  src/features/collection/constants/index.ts
  src/features/collection/types/index.ts
  src/features/collection/utils/getAllCapabilityBadgeItem.ts
  src/features/collection/utils/getExperiencePeriod.ts
  src/features/collection/utils/getFilteredExperiences.ts
  src/features/collection/utils/getSortedExperiences.ts
  src/hooks/reactQuery/experience/qeury.ts
  src/hooks/useIntersection.ts
  src/shared/constants/querykeys.ts
  src/shared/utils/addPlusMarkOver99.ts
  src/styles/theme/components/modalTheme.ts
Labels: :sparkles: FEATURE

#122 fix: 자기소개서 라우트 연결 및 스타일 수정
  src/app/resume/[id]/page.tsx
  src/app/resumes/[questionId]/page.tsx
  src/app/resumes/layout.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/features/resume/components/Aside/DeleteModal.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/utils/getResumeRoute.ts
Labels: 🐛 BUG

#124 feat: 자기소개서 - 경험카드 리스트 api 연결
  src/apis/experience/experience.ts
  src/apis/experience/types/experience.ts
  src/components/Badge/Badge.module.scss
  src/features/collection/components/nav/ChipListNav.tsx
  src/features/collection/constants/index.ts
  src/features/collection/utils/getExperiencePeriod.ts
  src/features/resume/components/MyExperienceCard/ExperienceCard.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardDetail.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
  src/features/resume/components/MyExperienceCard/MyExperienceCard.tsx
  src/features/resume/components/MyExperienceCard/MyExperienceCardHeader.tsx
  src/features/resume/constants/cardCountPerLoad.ts
  src/features/resume/store/index.ts
  src/features/resume/types/store.ts
  src/hooks/reactQuery/experience/qeury.ts
  src/shared/constants/querykeys.ts
Labels: :sparkles: FEATURE

#128 feat: 자기소개서 NotFound 처리
  public/images/lumos-nocard.png
  src/apis/resume/question.ts
  src/apis/resume/resume.ts
  src/apis/resume/types/question.ts
  src/apis/resume/types/resume.ts
  src/app/resumes/[questionId]/page.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardDetail.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
  src/features/resume/components/NotFound/NotFound.stories.tsx
  src/features/resume/components/NotFound/NotFound.tsx
  src/features/resume/components/NotFound/NotFoundExperienceCard.tsx
  src/features/resume/components/NotFound/NotFoundResume.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/store/index.ts
  src/hooks/reactQuery/onboarding/mutation.ts
  src/hooks/reactQuery/resume/mutation.ts
  src/hooks/reactQuery/resume/question/mutation.ts
Labels: :sparkles: FEATURE

#126 refactor: 회원가입 및 로그인 보완
  .storybook/main.ts
  scripts/chromatic_publish.sh
  src/apis/user/user.ts
  src/app/template.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Home/FeedbackForm.tsx
  src/components/Home/FooterNav.tsx
  src/components/Home/Home.tsx
  src/components/Home/StartButton.tsx
  src/components/Icon/jobCategories/index.ts
  src/features/auth/components/AuthModal/AuthModal.tsx
  src/features/auth/components/AuthModal/Category/Category.module.scss
  src/features/auth/components/AuthModal/Category/Category.stories.tsx
  src/features/auth/components/AuthModal/Category/Category.tsx
  src/features/auth/components/AuthModal/ModalContents/CategoriesContents.stories.tsx
  src/features/auth/components/AuthModal/ModalContents/CategoriesContents.tsx
  src/features/auth/components/AuthModal/ModalContents/SignUpContents.tsx
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/auth/types/signUp.ts
  src/shared/constants/routes.ts
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#132 chore: 메타데이터 추가 및 파비콘 추가
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/robots.txt
  src/app/sitemap.ts
  src/shared/constants/metadata.ts
Labels: 🧹 CHORE

#130 fix: 자기소개서 - UI 수정 및 로직 수정
  src/apis/resume/types/question.ts
  src/app/resumes/[questionId]/page.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/components/SpellChecker/SpellChecker.tsx
  src/features/resume/components/SpellChecker/SpellErrorPreview.tsx
  src/features/resume/components/SpellChecker/SpellErrorResult.tsx
  src/hooks/reactQuery/resume/query.ts
  src/shared/utils/replacePatternToComponent.tsx
Labels: 🐛 BUG

#135 feat: 모아보기 - 경험카드 뒷면 마크업
  public/images/ai-keyword-recommend.png
  src/features/collection/components/cards/ExperienceCard/ExperienceCard.tsx
Labels: :lipstick: STYLE

#140 chore: favicon 변경 & openGraph 이미지 추가
  src/app/favicon.ico
  src/app/opengraph-image.png
  src/app/twitter-image.png
Labels: 🧹 CHORE

#139 feat&style: 경험분해 > experienceId 전역상태로 다루기 & 스타일 수정
  src/app/analyze/layout.tsx
  src/shared/store/experienceId.tsx
  src/shared/utils/callbackRefWithResizeHeight.ts
Labels: :lipstick: STYLE, ♻️ REFACTOR

#136 feat: 모아보기 - ActionList api 연동
  src/apis/experience/experience.ts
  src/apis/experience/types/experience.ts
  src/app/collection/resumes/page.tsx
  src/features/collection/components/cards/ExperienceListCard/ExperienceListCard.tsx
  src/features/collection/components/cards/ResumeAnswerModalCard.tsx
  src/features/collection/components/cards/ResumeCard.tsx
  src/hooks/reactQuery/experience/mutation.ts
Labels: :sparkles: FEATURE

#144 feat: 경험 분해 온보딩 모달
  public/images/analyze/img-analyze-onboarding.png
  src/app/demo/input/page.tsx
  src/app/demo/page.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Icon/IconNumber1.tsx
  src/components/Icon/IconNumber2.tsx
  src/components/Icon/IconNumber3.tsx
  src/components/demo/Card.tsx
  src/components/demo/List.tsx
  src/feature/analyze/experience/page.tsx
  src/feature/analyze/modal/OnboardingModal.tsx
  src/hooks/reactQuery/onboarding/query.ts
  src/shared/constants/querykeys.ts
Labels: :sparkles: FEATURE

#106 feat: 모아보기 - notFound
  public/images/lumos-cry.png
  src/app/collection/ai-recommends/page.tsx
  src/app/collection/not-found.tsx
  src/app/not-found.tsx
Labels: :sparkles: FEATURE

#105 feat: 모아보기 - ai 추천 자기소개서
  package.json
  src/apis/ai/ai.ts
  src/apis/ai/types/ai.ts
  src/app/collection/ai-recommends/page.tsx
  src/app/collection/experiences/page.tsx
  src/app/collection/resumes/page.tsx
  src/app/collection/template.tsx
  src/app/completed-experience-card/[experienceId]/page.tsx
  src/features/collection/components/cards/AiRecommendResumeCard.tsx
  src/features/collection/components/cards/ResumeAnswerModalCard.tsx
  src/features/collection/components/lists/AiRecommendResumeList.tsx
  src/features/collection/components/nav/ChipListNav.tsx
  src/features/collection/constants/index.ts
  src/hooks/reactQuery/ai/query.ts
  src/shared/constants/maxLength.ts
  tailwind.config.js
  yarn.lock
Labels: :sparkles: FEATURE

#145 Feat: 경험분석 완성 페이지 api 연동
  src/apis/analyze/types/experience.ts
  src/app/collection/not-found.tsx
  src/app/collection/resumes/page.tsx
  src/app/completed-experience-card/[experienceId]/layout.tsx
  src/app/completed-experience-card/[experienceId]/page.tsx
  src/app/completed-experience-card/layout.tsx
  src/app/completed-experience-card/page.tsx
  src/feature/analyze/complete/components/CompletePage.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceCard.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceModal.tsx
  src/features/collection/components/cards/ExperienceListCard/ExperienceListCard.tsx
  src/features/collection/types/index.ts
  src/features/experience/Wrapper.tsx
  src/features/resume/utils/getResumeRoute.ts
Labels: :sparkles: FEATURE

#147 feat: 경험분해 페이지 이탈시 noticeModal 띄우기
  src/app/analyze/layout.tsx
  src/app/template.tsx
  src/shared/store/boolean.ts
  src/shared/store/experienceId.tsx
Labels: :sparkles: FEATURE

#148 chore: feature => features 폴더로 이주
  src/apis/analyze/experience.ts
  src/apis/analyze/types/experience.ts
  src/apis/analyze/types/keyword.ts
  src/apis/experience/types/experience.ts
  src/app/analyze/experience/page.tsx
  src/app/analyze/information/page.tsx
  src/app/analyze/keyword/page.tsx
  src/app/analyze/layout.tsx
  src/app/analyze/verify/page.tsx
  src/components/Progress/Progress.tsx
  src/components/Stepper/Stepper.tsx
  src/features/analyze/PrevNextButton/PrevNextButton.tsx
  src/features/analyze/constants/index.ts
  src/features/analyze/experience/PickerFieldContainer.tsx
  src/features/analyze/experience/page.tsx
  src/features/analyze/information/page.tsx
  src/features/analyze/keyword/KeywordContainer.tsx
  src/features/analyze/keyword/page.tsx
  src/features/analyze/layout/StepMenu.tsx
  src/features/analyze/layout/StepMenuItem.module.scss
  src/features/analyze/layout/StepMenuItem.tsx
  src/features/analyze/modal/BaseDialog.tsx
  src/features/analyze/modal/LoadingModal.tsx
  src/features/analyze/modal/OnboardingModal.tsx
  src/features/analyze/types/index.ts
  src/features/analyze/verify/AICapabilityKeyword.tsx
  src/features/analyze/verify/AIResumeLoading.tsx
  src/features/analyze/verify/RecommendKeyword.tsx
  src/features/analyze/verify/SelectedKeywordContainer.tsx
  src/features/analyze/verify/page.tsx
  src/features/collection/components/cards/CapabilityImage.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceCard.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceModal.tsx
  src/hooks/reactQuery/analyze/mutation.ts
Labels: 🧹 CHORE

#146 fix: 자기소개서 오류 수정
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Title.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCard.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardDetail.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/components/SpellChecker/SpellChecker.tsx
  src/features/resume/store/index.ts
  src/hooks/reactQuery/resume/mutation.ts
  src/hooks/reactQuery/resume/question/mutation.ts
  src/shared/constants/maxLength.ts
Labels: 🐛 BUG

#157 chore: Google Analytics & Hotjar 추가
  src/app/layout.tsx
  src/components/GoogleAnalytics/GoogleAnalytics.tsx
  src/components/Hotjar/Hotjar.tsx
Labels: 🧹 CHORE

#161 feat: PC 해상도가 아닌경우 PC 접속 권장 안내 화면 보여주기
  src/app/template.tsx
  src/components/OnlyPCSupport/OnlyPCSupport.tsx
  src/hooks/useMediaQuery.ts
Labels: :sparkles: FEATURE

#164 fix: 맞춤법 검사 시, 레이아웃 높이 변경되는 이슈 수정
  src/app/resumes/[questionId]/page.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
Labels: 🐛 BUG

#154 Feat: 모아보기 notFound 라우트 이동
  src/app/collection/loading.tsx
  src/app/collection/not-found.tsx
  src/features/collection/constants/index.ts
  src/features/collection/types/index.ts
  src/shared/constants/routes.ts
Labels: :sparkles: FEATURE

#158 Feat: 경험카드 api 누락 데이터 추가
  src/apis/analyze/types/experience.ts
  src/feature/analyze/complete/components/CompletePage.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceCard.tsx
  src/features/collection/components/cards/ExperienceCard/ExperienceModal.tsx
  src/features/collection/components/cards/ExperienceListCard/ExperienceListCard.tsx
  src/features/collection/types/index.ts
  src/shared/constants/maxLength.ts
Labels: :sparkles: FEATURE

#169 style: ChipListNav 왼쪽 잘려서 보이는 스타일 수정
  src/features/collection/components/nav/ChipListNav.tsx
Labels: :lipstick: STYLE

#178 fix: 내 경험카드 조회 시, s,t,a,r 전부 true로 수정
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
Labels: 🐛 BUG

#183 refactor: 키워드 선택하고 추가하기 시에 깜빡거리는 현상 제거
  src/features/analyze/keyword/page.tsx
  src/hooks/reactQuery/keyword/mutation.ts
Labels: ♻️ REFACTOR

#184 refactor: 경험카드 만들기 페이지 prefetch
  src/feature/analyze/complete/components/CompletePage.tsx
  src/features/analyze/verify/page.tsx
Labels: ♻️ REFACTOR

#188 fix: 자기소개서 항목 누를 때마다 제목 바뀌는 오류 해결
  src/features/resume/hooks/useResumeListWithUpdatedTitle.ts
Labels: 🐛 BUG
