Repository depromeet/InsightOut-client, pull requests merged in 2023-08, with the labels that each got.

#197 hotfix: production BASE_URL 변경
  src/shared/constants/http.ts
Labels: :ambulance: HOTFIX

#194 QA 반영 & yup으로 경험분해 페이지 폼 데이터 유효성 검사
  package.json
  src/app/analyze/layout.tsx
  src/app/globals.css
  src/app/template.tsx
  src/components/Input/ErrorMessage.tsx
  src/components/OnlyPCSupport/OnlyPCSupport.tsx
  src/features/ExperienceFormProvider.tsx
  src/features/analyze/experience/page.tsx
  src/features/analyze/layout/index.tsx
  src/hooks/useBlockScroll.ts
  yarn.lock
Labels: ♻️ REFACTOR

#195 feat&refactor: AI 추천 자기소개서 Blocking UI 에서 Streaming UI으로 리팩토링
  package.json
  src/apis/analyze/experience.ts
  src/app/api/chat/route.ts
  src/features/ExperienceFormProvider.tsx
  src/features/analyze/PrevNextButton/PrevNextButton.tsx
  src/features/analyze/constants/index.ts
  src/features/analyze/layout/index.tsx
  src/features/analyze/types/index.ts
  src/features/analyze/verify/AIRecommendResume.tsx
  src/features/analyze/verify/AIResumeLoading.tsx
  src/features/analyze/verify/page.tsx
  yarn.lock
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#199 refactor: 자기소개서 페이지 로딩 속도 개선
  src/app/resumes/@aside/default.tsx
  src/app/resumes/@myExperienceCard/default.tsx
  src/app/resumes/@resume/[questionId]/page.tsx
  src/app/resumes/@resume/default.tsx
  src/app/resumes/layout.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/features/resume/components/Aside/Resume/Resume.tsx
  src/features/resume/components/MyExperienceCard/ExperienceCardList.tsx
  src/features/resume/components/MyExperienceCard/MyExperienceCard.stories.tsx
  src/features/resume/components/ResumeForm/ResumeForm.stories.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/hooks/reactQuery/resume/query.ts
Labels: ♻️ REFACTOR
