Repository depromeet/InsightOut-client, pull requests merged in 2023-06, with the labels that each got.

#21 feat: Chip 컴포넌트 제작
  src/components/Button/Button.tsx
  src/components/Button/TextButton.module.scss
  src/components/Button/TextButton.tsx
  src/components/Chip/Badge.module.scss
  src/components/Chip/Badge.tsx
  src/components/Chip/Chip.module.scss
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/services/@types/button.d.ts
  src/services/@types/component.d.ts
  src/services/@types/scss.d.ts
  yarn.lock
Labels: :lipstick: STYLE

#26 feat: Badge 컴포넌트
  src/components/Badge/Badge.module.scss
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/services/@types/component.d.ts
Labels: :lipstick: STYLE

#22 Feat/modal compound
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/app/demo/page.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/ModalHeader.tsx
  src/styles/theme/components/modalTheme.ts
  src/styles/theme/index.ts
  yarn.lock
Labels: :lipstick: STYLE, :sparkles: FEATURE

#28 refactor: Chip with Badge 컴포넌트에 Badge 컴포넌트 반영
  src/components/Badge/Badge.module.scss
  src/components/Chip/Badge.module.scss
  src/components/Chip/Badge.tsx
  src/components/Chip/Chip.stories.tsx
Labels: ♻️ REFACTOR

#45 feat: Tab 컴포넌트
  src/components/Button/Button.tsx
  src/components/Button/TextButton.tsx
  src/components/Chip/Chip.tsx
  src/components/Tab/Tab.module.scss
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/services/@types/component.d.ts
Labels: :lipstick: STYLE

#30 feat: ActionList 컴포넌트
  .storybook/main.ts
  .storybook/preview.tsx
  src/app/layout.tsx
  src/components/ActionList/ActionList.stories.tsx
  src/components/ActionList/ActionList.tsx
Labels: :lipstick: STYLE

#53 style: purple => primary , cyan => secondary로 color name 수정
  src/app/globals.css
  src/app/page.tsx
  src/components/Badge/Badge.module.scss
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/TextButton.module.scss
  src/components/Chip/Chip.module.scss
  src/components/Chip/Chip.stories.tsx
  src/components/Input/TextLengthMessage.tsx
  src/components/Tag/Tag.module.scss
  src/services/@types/component.d.ts
  src/styles/theme/foundations/colors.ts
Labels: :lipstick: STYLE

#56 feat: Tag 컴포넌트 variant 추가
  src/components/Tag/Tag.module.scss
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/Tag.tsx
  src/services/@types/component.d.ts
  src/services/@types/tag.d.ts
Labels: :lipstick: STYLE

#52 feat: LNB/ResumeItem 컴포넌트
  .storybook/main.ts
  src/components/Icon/IconDocument.tsx
  src/components/Icon/IconFolder.tsx
  src/components/Icon/IconMoreVertical.tsx
  src/components/Icon/IconPlus.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Question.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Question.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/QuestionAddButton.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/QuestionAddButton.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.tsx
  tailwind.config.js
Labels: :lipstick: STYLE

#36 feat: 경험분해 기초작업 (폴더구조 잡기, 레이아웃 구성, 라우팅 가드)
  next.config.js
  package.json
  src/app/analyze/experience/page.tsx
  src/app/analyze/information/page.tsx
  src/app/analyze/keyword/page.tsx
  src/app/analyze/layout.tsx
  src/app/analyze/template.tsx
  src/app/analyze/verify/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/QuestionCard/QuestionCard.tsx
  src/middleware.ts
  src/shared/constants/routes.tsx
Labels: :sparkles: FEATURE

#47 feat: 모아보기 Next 13 app router layout 설정
  src/app/collection/ai-recommends/page.tsx
  src/app/collection/experiences/page.tsx
  src/app/collection/layout.tsx
  src/app/collection/loading.tsx
  src/app/collection/not-found.tsx
  src/app/collection/resumes/page.tsx
  src/app/collection/template.tsx
  src/app/globals.css
  src/components/Badge/Badge.tsx
  src/components/Tab/Tab.module.scss
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/middleware.ts
  src/services/@types/component.d.ts
  src/shared/constants/tabs.tsx
Labels: :sparkles: FEATURE

#60 fix: Link href type 에러로 build 실패 해결
  src/app/resume/[id]/page.tsx
  src/components/Tab/Tab.tsx
  src/shared/@types/route.d.ts
Labels: 🐛 BUG

#58 feat: Tooltip 컴포넌트
  jest.config.js
  jest.setup.js
  package.json
  src/components/Badge/Badge.tsx
  src/components/Icon/IconTooltipTailBottom.tsx
  src/components/Icon/IconTooltipTailLeft.tsx
  src/components/Icon/IconTooltipTailRight.tsx
  src/components/Icon/IconTooltipTailTop.tsx
  src/components/Tooltip/Tooltip.module.scss
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/services/@types/component.d.ts
  src/services/utils/wrapTooltipChildren.test.tsx
  src/services/utils/wrapTooltipChildren.tsx
  src/styles/theme/foundations/dropShadow.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: :lipstick: STYLE

#63 feat: Tooltip 컴포넌트 사용 방식 구현
  src/components/Icon/IconTooltipArrowBottom.tsx
  src/components/Icon/IconTooltipArrowLeft.tsx
  src/components/Icon/IconTooltipArrowRight.tsx
  src/components/Icon/IconTooltipArrowTop.tsx
  src/components/Tooltip/Tooltip.module.scss
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipArrow.module.scss
  src/components/Tooltip/TooltipArrow.tsx
  src/components/Tooltip/TooltipContent.module.scss
  src/components/Tooltip/TooltipContent.tsx
  src/services/@types/component.d.ts
  src/services/constants/tooltip.ts
  src/services/utils/tooltip/getPlacement.test.tsx
  src/services/utils/tooltip/getPlacement.ts
  src/services/utils/tooltip/wrapTooltipChildren.test.tsx
  src/services/utils/tooltip/wrapTooltipChildren.tsx
Labels: :lipstick: STYLE, :sparkles: FEATURE

#59 feat: LNB 컴포넌트
  src/app/resumes/[questionId]/page.tsx
  src/app/resumes/layout.tsx
  src/components/Icon/IconPencil.tsx
  src/feature/resume/components/LeftNavigationBar/LeftNavigationBar.stories.tsx
  src/feature/resume/components/LeftNavigationBar/LeftNavigationBar.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/Resume.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/Resume.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Question.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Question.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/QuestionAddButton.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.stories.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeListContainer.tsx
  src/services/@types/data/question.ts
  src/services/@types/data/resume.ts
  src/shared/constants/routes.ts
Labels: :sparkles: FEATURE

#64 fix: route 파일 중복 제거 / services 폴더 → shared 폴더
  src/app/resumes/layout.tsx
  src/components/Icon/IconDocument.tsx
  src/components/Icon/IconFolder.tsx
  src/components/Icon/IconMoreVertical.tsx
  src/components/Icon/IconPencil.tsx
  src/components/Icon/IconPlus.tsx
  src/components/Input/TextAreaField/TextAreaField.tsx
  src/components/Input/TextField/TextField.tsx
  src/components/Input/TextLengthMessage.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipArrow.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/feature/resume/components/LeftNavigationBar/LeftNavigationBar.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/Resume.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Question.tsx
  src/feature/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.tsx
  src/shared/@types/component.d.ts
  src/shared/@types/data/question.ts
  src/shared/@types/data/resume.ts
  src/shared/@types/global.d.ts
  src/shared/@types/scss.d.ts
  src/shared/@types/svg.d.ts
  src/shared/constants/routes.ts
  src/shared/constants/routes.tsx
  src/shared/constants/tooltip.ts
  src/shared/utils/autoSizeTextarea.ts
  src/shared/utils/tailwindMerge.ts
  src/shared/utils/tooltip/getPlacement.test.tsx
  src/shared/utils/tooltip/getPlacement.ts
  src/shared/utils/tooltip/wrapTooltipChildren.test.tsx
  src/shared/utils/tooltip/wrapTooltipChildren.tsx
Labels: 🐛 BUG

#67 chore: Chip, Badge 컴포넌트 디자인시스템 동기화
  src/app/collection/template.tsx
  src/components/Badge/Badge.module.scss
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Chip/Chip.module.scss
  src/components/Chip/Chip.stories.tsx
  src/components/Tab/Tab.module.scss
  src/components/Tab/Tab.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/Tag.tsx
  src/shared/@types/component.d.ts
Labels: 🧹 CHORE

#69 fix&style: button 디자인 가이드 관련 추가 수정
  src/components/Button/Button.module.scss
  src/components/Button/TextButton.module.scss
Labels: :lipstick: STYLE

#68 Feat/tag Tag 컴포넌트 디자인시스템 동기화
  src/components/Input/TextAreaField/TextAreaField.tsx
  src/components/Input/TextField/TextField.tsx
  src/components/Tag/Tag.module.scss
  src/components/Tag/Tag.stories.tsx
  src/shared/@types/component.d.ts
Labels: 🧹 CHORE

#71 feat: GNB
  build-storybook.log
  scripts/chromatic_publish.sh
  src/apis/index.ts
  src/app/collection/template.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/template.tsx
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Chip/Chip.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Icon/IconGoogleLogo.tsx
  src/components/Providers/ChakraProvider.tsx
  src/components/Providers/TanstackQueryProvider.tsx
  src/components/Tab/Tab.stories.tsx
  src/feature/auth/components/Providers/AuthProvider.tsx
  src/feature/auth/hooks/useGoogleLogin.ts
  src/feature/auth/store/index.ts
  src/feature/auth/types/index.ts
  src/shared/utils/emptyFunction.ts
  src/styles/theme/foundations/dropShadow.ts
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#61 feat: 경험분해 - 경험정보 (/analyze/experience)
  package.json
  src/app/analyze/experience/page.tsx
  src/app/analyze/information/page.tsx
  src/app/analyze/keyword/page.tsx
  src/app/analyze/layout.tsx
  src/app/analyze/template.tsx
  src/app/demo/input/page.tsx
  src/components/Input/ErrorMessage.tsx
  src/components/Input/RHFTextAreaField/RHFTextAreaField.tsx
  src/components/Input/TextField/TextField.tsx
  src/components/QuestionCard/QuestionCard.tsx
  src/feature/analyze/analyze.constants.ts
  src/feature/analyze/analyze.types.ts
  src/feature/analyze/experience/PickerFieldContainer.tsx
  src/hooks/useIsMounted.ts
  src/shared/@types/component.d.ts
  src/shared/utils/callbackRefWithResizeHeight.ts
  yarn.lock
Labels: :sparkles: FEATURE

#83 feat: Refresh Token 재발급하여 로그인 유지
  src/apis/auth.ts
  src/apis/index.ts
  src/app/layout.tsx
  src/app/template.tsx
  src/feature/auth/components/Providers/AuthProvider.tsx
  src/features/auth/components/Providers/AuthProvider.tsx
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/auth/shared/constants/api.ts
  src/features/auth/store/index.ts
  src/features/auth/types/data.ts
  src/features/auth/types/store.ts
  src/shared/@types/data/api.ts
  src/shared/constants/http.ts
Labels: :sparkles: FEATURE

#70 feat: 경험 분해 - 직무역량 키워드 (/analyze/keyword)
  src/app/analyze/keyword/page.tsx
  src/app/globals.css
  src/components/Tag/Tag.module.scss
  src/feature/analyze/keyword/KeywordContainer.tsx
  src/hooks/useInput.ts
  src/shared/utils/exceptEnter.ts
Labels: :sparkles: FEATURE

#91 refactor: LeftNavigationBar -> Aside
  src/app/resumes/[questionId]/page.tsx
  src/app/resumes/layout.tsx
  src/feature/resume/store/index.ts
  src/feature/resume/types/store.ts
  src/features/resume/components/Aside/Aside.stories.tsx
  src/features/resume/components/Aside/Aside.tsx
  src/features/resume/components/Aside/Resume/Resume.stories.tsx
  src/features/resume/components/Aside/Resume/Resume.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.stories.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/QuestionAddButton.stories.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/QuestionAddButton.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Title.stories.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Title.tsx
  src/features/resume/components/Aside/Resume/ResumeListContainer.tsx
  src/features/resume/components/ResumeForm/ResumeForm.stories.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/components/ResumeForm/SavingCaption.tsx
  src/features/resume/constants/savingStatus.ts
  src/features/resume/store/index.ts
  src/features/resume/types/question.ts
  src/features/resume/types/resume.ts
  src/features/resume/types/store.ts
  tailwind.config.js
Labels: ♻️ REFACTOR

#73 feat: 경험분해 - 경험내용, AI 직무역량 페이지 퍼블리싱
  next.config.js
  package.json
  public/icons/alert-circle-line.svg
  src/app/analyze/information/page.tsx
  src/app/analyze/verify/page.tsx
  src/components/Icon/AlertCircleLine.tsx
  src/components/Icon/index.ts
  src/components/Input/TextAreaField/TextAreaField.tsx
  src/feature/analyze/verify/AICapabilityKeyword.tsx
  src/feature/analyze/verify/RecommendKeyword.tsx
  src/feature/analyze/verify/SelectedKeywordContainer.tsx
Labels: :lipstick: STYLE, :sparkles: FEATURE

#97 feat: 로그인 유지 기능 수정, 자동 로그인, 토큰 존재하지 않을 경우 처리
  package.json
  src/apis/auth/auth.ts
  src/apis/auth/types/auth.ts
  src/apis/index.ts
  src/app/template.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.stories.tsx
  src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Spinner/Spinner.tsx
  src/components/Tag/Tag.stories.tsx
  src/features/auth/components/Providers/AuthProvider.tsx
  src/features/auth/hooks/useGoogleLogin.ts
  src/features/auth/store/index.ts
  src/features/auth/types/store.ts
  src/shared/@types/component.d.ts
  src/shared/@types/data/api.ts
  src/shared/constants/http.ts
  src/shared/constants/routes.ts
  src/shared/constants/spinner.ts
  src/shared/constants/tabs.ts
  src/shared/utils/http.ts
  yarn.lock
Labels: ♻️ REFACTOR, :sparkles: FEATURE

#102 refactor: http base url production 환경 적용
  src/shared/constants/http.ts
Labels: ♻️ REFACTOR

#95 feat: 자기소개서 - 맞춤법 검사 컴포넌트
  package.json
  src/components/Icon/IconCheckCircle.tsx
  src/components/Icon/IconCheckLine.tsx
  src/components/Icon/IconReset.tsx
  src/components/Icon/IconXLine.tsx
  src/components/Icon/index.ts
  src/feature/analyze/verify/AICapabilityKeyword.tsx
  src/features/resume/components/SpellChecker/ErrorWord.tsx
  src/features/resume/components/SpellChecker/SpellCheckTitle.tsx
  src/features/resume/components/SpellChecker/SpellChecker.stories.tsx
  src/features/resume/components/SpellChecker/SpellChecker.tsx
  src/features/resume/components/SpellChecker/SpellErrorPreview.tsx
  src/features/resume/components/SpellChecker/SpellErrorResult.tsx
  src/features/resume/hooks/useSpellCheckResult.ts
  src/features/resume/store/index.ts
  src/features/resume/types/question.ts
  src/features/resume/types/store.ts
  src/shared/utils/replacePatternToComponent.tsx
Labels: :lipstick: STYLE, :sparkles: FEATURE

#93 feat: 자기소개서 - Aside api 연결
  src/apis/resume/resume.ts
  src/apis/resume/types/resume.ts
  src/app/resumes/layout.tsx
  src/components/Icon/IconCheckCircle.tsx
  src/components/Icon/IconCheckLine.tsx
  src/components/Icon/IconReset.tsx
  src/components/Icon/IconXLine.tsx
  src/features/resume/components/Aside/Aside.stories.tsx
  src/features/resume/components/Aside/Aside.tsx
  src/features/resume/components/Aside/Resume/Resume.stories.tsx
  src/features/resume/components/Aside/Resume/Resume.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Title.tsx
  src/features/resume/components/Aside/Resume/ResumeListContainer.tsx
  src/features/resume/components/SpellChecker/SpellCheckTitle.tsx
  src/features/resume/components/SpellChecker/SpellChecker.tsx
  src/features/resume/components/SpellChecker/SpellErrorPreview.tsx
  src/features/resume/components/SpellChecker/SpellErrorResult.tsx
  src/features/resume/hooks/useSpellCheckResult.ts
  src/hooks/reactQuery/resume/mutation.ts
  src/hooks/reactQuery/resume/query.ts
  src/shared/constants/querykeys.ts
Labels: :sparkles: FEATURE

#99 feat: 자기소개서 - 자동저장 기능
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/constants/autoSaveTime.ts
  src/hooks/useDebounce.ts
Labels: :sparkles: FEATURE

#103 feat: 자기소개서 - 자기소개서 작성 api 연결
  src/apis/resume/question.ts
  src/apis/resume/resume.ts
  src/apis/resume/types/question.ts
  src/app/resumes/[questionId]/page.tsx
  src/app/resumes/layout.tsx
  src/components/Icon/IconVerticalDivider.tsx
  src/features/resume/components/Aside/Aside.tsx
  src/features/resume/components/Aside/Resume/Resume.tsx
  src/features/resume/components/Aside/Resume/ResumeItem/Question.tsx
  src/features/resume/components/ResumeForm/ResumeForm.stories.tsx
  src/features/resume/components/ResumeForm/ResumeForm.tsx
  src/features/resume/components/ResumeForm/SavingCaption.tsx
  src/features/resume/components/SpellChecker/SpellErrorPreview.tsx
  src/features/resume/components/SpellChecker/SpellErrorResult.tsx
  src/hooks/reactQuery/resume/mutation.ts
  src/hooks/reactQuery/resume/question/mutation.ts
  src/hooks/reactQuery/resume/question/query.ts
  src/shared/constants/querykeys.ts
  src/shared/utils/date/formatYYMMDDhhmm.ts
Labels: :sparkles: FEATURE
